In [2]:
# pip install numpy
import numpy as np 

In [3]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1 boyutlu dizi:", array_1d)

1 boyutlu dizi: [1 2 3 4 5]


In [6]:
array_1d[0] + array_1d[-1]

6

In [7]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2 boyutlu dizi:\n", array_2d)

2 boyutlu dizi:
 [[1 2 3]
 [4 5 6]]


In [8]:
zeros_array = np.zeros((2, 3)) 
print("Sifirlardan oluşan dizi\n", zeros_array)

Sifirlardan oluşan dizi
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ones_array = np.ones((3, 4)) 
print("Birlerden oluşan dizi\n", ones_array)

Birlerden oluşan dizi
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
range_array = np.arange(1, 250, 50) 
print("Belirli araliktaki dizi:", range_array)

Belirli araliktaki dizi: [  1  51 101 151 201]


In [13]:
arr = np.linspace(1, 100, 6)
print('Dizi\n', arr)

Dizi
 [  1.   20.8  40.6  60.4  80.2 100. ]


In [14]:
array = np.array([1, 2, 3, 4, 5])
print('Karesi alinmis dizi\n', np.square(array))

Karesi alinmis dizi
 [ 1  4  9 16 25]


In [15]:
array = np.array([1, 16, 81, 100, 625])
print('Karekoku alinmis dizi\n', np.sqrt(array))

Karekoku alinmis dizi
 [ 1.  4.  9. 10. 25.]


In [16]:
array_list = np.array([1, 5, 69, 48, 128, 73, 55398, 373])
print('Dizi elemanlari toplami: ', np.sum(array_list))
print('Dizinin ortanca sayisi: ', np.median(array_list))
print('Dizinin elemanlarini ortalamasi: ', np.mean(array_list))

Dizi elemanlari toplami:  56095
Dizinin ortanca sayisi:  71.0
Dizinin elemanlarini ortalamasi:  7011.875


In [17]:
array1 = np.array([5, 6, 10, 68, 59])
array2 = np.array([1, 458, 834, 438])

print('İki dizinin toplami:', (array1-array2))

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [18]:
array1 = np.array([5, 6, 10, 68, 59])
array2 = np.array([1, 458, 834, 438, 24])

print('İki dizinin toplami:', (array1+array2))
print('İki dizinin farki:', (array1-array2))

print('1.dizinin 3.elemani ile 2.dizinin 1.elemaninin farki: ', array1[2]-array2[0])

İki dizinin toplami: [  6 464 844 506  83]
İki dizinin farki: [   4 -452 -824 -370   35]
1.dizinin 3.elemani ile 2.dizinin 1.elemaninin farki:  9


In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 10, 15])

print('İki dizinin carpimi: ', arr1*arr2)
print('İki dizinin bölümü: ', arr1/arr2)
print('İki dizinin bölümü: ', arr1//arr2) # // işareti, bize bölme işlemini yaparken ondalık kesri görmezden gelip tam sayı değerini yazdırır!

İki dizinin carpimi:  [ 5 20 45]
İki dizinin bölümü:  [0.2 0.2 0.2]
İki dizinin bölümü:  [0 0 0]


In [21]:
array = np.arange(1, 200, 12)
print("Dizinin son elemani: ", array[-1])
print("Dizinin ilk 5 elemani ", array[:5]) # (1, 3]
print("Dizinin son 5 elemani: ", array[-5:])

Dizinin son elemani:  193
Dizinin ilk 5 elemani  [ 1 13 25 37 49]
Dizinin son 5 elemani:  [145 157 169 181 193]


In [22]:
# pip install pandas

import pandas as pd

In [25]:
data = {
    'Matematik': np.random.randint(0, 100, 20),
    'Ingilizce': np.random.randint(0, 100, 20)
}

df = pd.DataFrame(data)

In [27]:
df.head() # İlk 5 satır örneğini verir

Matematik  Ingilizce
0         11         54
1         35         54
2         80         80
3         83         39
4         33          8
5         97         58
6         80         77
7         49         51
8          8         19
9         61         72

In [29]:
df.tail(10) # Son 5 satırı getirir

Matematik  Ingilizce
10         48         10
11          1         59
12         91         45
13         30         46
14          7         95
15         59         79
16          5         26
17         47         27
18         86         27
19         70         33

In [32]:
df[df['Matematik']>50]['Matematik']

2     80
3     83
5     97
6     80
9     61
12    91
15    59
18    86
19    70
Name: Matematik, dtype: int32

In [33]:
df[df['Ingilizce']>80]['Ingilizce']

14    95
Name: Ingilizce, dtype: int32

In [34]:
df['Ortalama'] = (df['Matematik'] + df['Ingilizce']) / 2

In [35]:
df

Matematik  Ingilizce  Ortalama
0          11         54      32.5
1          35         54      44.5
2          80         80      80.0
3          83         39      61.0
4          33          8      20.5
5          97         58      77.5
6          80         77      78.5
7          49         51      50.0
8           8         19      13.5
9          61         72      66.5
10         48         10      29.0
11          1         59      30.0
12         91         45      68.0
13         30         46      38.0
14          7         95      51.0
15         59         79      69.0
16          5         26      15.5
17         47         27      37.0
18         86         27      56.5
19         70         33      51.5