In [1]:
import numpy as np 

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1 boyutlu dizi:", array_1d)

1 boyutlu dizi: [1 2 3 4 5]


In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2 boyutlu dizi:\n", array_2d)

2 boyutlu dizi:
 [[1 2 3]
 [4 5 6]]


In [4]:
zeros_array = np.zeros((2, 3)) 
print("Sifirlardan oluşan dizi\n", zeros_array)

Sifirlardan oluşan dizi
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones_array = np.ones((3, 4)) 
print("Birlerden oluşan dizi\n", ones_array)

Birlerden oluşan dizi
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
range_array = np.arange(1, 10, 2) 
print("Belirli araliktaki dizi:", range_array)

Belirli araliktaki dizi: [1 3 5 7 9]


In [7]:
arr = np.linspace(1, 100, 4)
print('Dizi\n', arr)

Dizi
 [  1.  34.  67. 100.]


In [8]:
array = np.array([1, 2, 3, 4, 5])
print('Karesi alinmis dizi\n', np.square(array))

Karesi alinmis dizi
 [ 1  4  9 16 25]


In [9]:
array = np.array([1, 16, 81, 100, 625])
print('Karekoku alinmis dizi\n', np.sqrt(array))

Karekoku alinmis dizi
 [ 1.  4.  9. 10. 25.]


In [10]:
array_list = np.array([1, 5, 69, 48, 128])
print('Dizi elemanlari toplami: ', np.sum(array_list))
print('Dizinin ortanca sayisi: ', np.median(array_list))
print('Dizinin elemanlarini ortalamasi: ', np.mean(array_list))

Dizi elemanlari toplami:  251
Dizinin ortanca sayisi:  48.0
Dizinin elemanlarini ortalamasi:  50.2


In [11]:
array1 = np.array([5, 6, 10, 68, 59])
array2 = np.array([1, 458, 834, 438])

print('İki dizinin toplami:', (array1-array2))

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [12]:
array1 = np.array([5, 6, 10, 68, 59])
array2 = np.array([1, 458, 834, 438, 24])

print('İki dizinin toplami:', (array1+array2))
print('İki dizinin farki:', (array1-array2))

İki dizinin toplami: [  6 464 844 506  83]
İki dizinin farki: [   4 -452 -824 -370   35]


In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 10, 15])

print('İki dizinin carpimi: ', arr1*arr2)
print('İki dizinin bölümü: ', arr1/arr2)

İki dizinin carpimi:  [ 5 20 45]
İki dizinin bölümü:  [0.2 0.2 0.2]


In [14]:
array = np.arange(1, 200, 12)
print("Dizinin son elemani: ", array[-1])
print("Dizinin ilk 5 elemani ", array[:5])
print("Dizinin son 5 elemanı: ", array[-5:])

Dizinin son elemani:  193
Dizinin ilk 5 elemani  [ 1 13 25 37 49]
Dizinin son 5 elemanı:  [145 157 169 181 193]
